/* eslint-disable */
/* prettier-ignore */
// biome-ignore format: off
// biome-ignore lint: off
// @ts-nocheck
// Generated by unplugin-svg-component
import 'vue'
declare module 'vue' {
  export interface GlobalComponents {
    SvgIcon: import("vue").DefineComponent<{
        name: {
            type: import("vue").PropType<"add" | "calendar" | "close" | "dashboard" | "delete" | "downward - area" | "downward - linear" | "edit" | "export" | "fullscreen-exit" | "fullscreen" | "Import" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "left-area" | "Left-linear" | "omit" | "Print" | "question" | "right-area" | "Right-linear" | "search" | "service" | "set" | "up - linear" | "up and down arrows" | "up-area">;
            default: string;
            required: true;
        };
    }, {}, unknown, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<import("vue").ExtractPropTypes<{
        name: {
            type: import("vue").PropType<"add" | "calendar" | "close" | "dashboard" | "delete" | "downward - area" | "downward - linear" | "edit" | "export" | "fullscreen-exit" | "fullscreen" | "Import" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "left-area" | "Left-linear" | "omit" | "Print" | "question" | "right-area" | "Right-linear" | "search" | "service" | "set" | "up - linear" | "up and down arrows" | "up-area">;
            default: string;
            required: true;
        };
    }>>, {
        name: "add" | "calendar" | "close" | "dashboard" | "delete" | "downward - area" | "downward - linear" | "edit" | "export" | "fullscreen-exit" | "fullscreen" | "Import" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "left-area" | "Left-linear" | "omit" | "Print" | "question" | "right-area" | "Right-linear" | "search" | "service" | "set" | "up - linear" | "up and down arrows" | "up-area";
    }>;
  }
}
